### ISSUE TITLE
Nit: change type hint to generic types to support python < 3.9?

### ISSUE THREAD

**Issue by lchu6** [IBM/hod-archive-sdk-python#1]
We just started using this toolkit for pulling HOD data and found a nit:

In the script, the type hint is using non-generic types (e.g. `dict[str, Any]` rather than `typing.Dict[str, Any]`).  Although this works in python 3.9+ where dict can be used as generic type for inferencing, it might be more common to use typing classes for compatibility as many systems are still using python 3.8.

**Comment by erik-goepfert** [comment]
Resolved with [v1.0.1](https://github.com/IBM/hod-archive-sdk-python/releases/tag/v1.0.1)
